services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_embed_demo_development
      PGPORT: 5444
    ports:
      - "5444:5444"

volumes:
  postgres:
